// <auto-generated />
using System;
using GestionComplejo2C.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionComplejo2C.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SportsComplexDbContext))]
    [Migration("20260922203635_AddUsuariosYReservaCliente")]
    partial class AddUsuariosYReservaCliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CanchaServicio", b =>
                {
                    b.Property<Guid>("CanchasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiciosId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CanchasId", "ServiciosId");

                    b.HasIndex("ServiciosId");

                    b.ToTable("CanchaServicio");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Cancha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Deporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JugadoresMax")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioPorHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoPiso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VestuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VestuarioId")
                        .IsUnique()
                        .HasFilter("[VestuarioId] IS NOT NULL");

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Cancelada")
                        .HasColumnType("bit");

                    b.Property<Guid>("CanchaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Horas")
                        .HasColumnType("int");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Servicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Vestuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<int>("Duchas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vestuarios");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Administrador", b =>
                {
                    b.HasBaseType("GestionComplejo2C.Domain.Entities.Usuario");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Cliente", b =>
                {
                    b.HasBaseType("GestionComplejo2C.Domain.Entities.Usuario");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("CanchaServicio", b =>
                {
                    b.HasOne("GestionComplejo2C.Domain.Entities.Cancha", null)
                        .WithMany()
                        .HasForeignKey("CanchasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionComplejo2C.Domain.Entities.Servicio", null)
                        .WithMany()
                        .HasForeignKey("ServiciosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Cancha", b =>
                {
                    b.HasOne("GestionComplejo2C.Domain.Entities.Vestuario", "Vestuario")
                        .WithOne("Cancha")
                        .HasForeignKey("GestionComplejo2C.Domain.Entities.Cancha", "VestuarioId");

                    b.Navigation("Vestuario");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("GestionComplejo2C.Domain.Entities.Cancha", null)
                        .WithMany("Reservas")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionComplejo2C.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Cancha", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Vestuario", b =>
                {
                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
