// <auto-generated />
using System;
using GestionComplejo2C.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionComplejo2C.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SportsComplexDbContext))]
    [Migration("20260929193917_TranslateSchemaToEnglish")]
    partial class TranslateSchemaToEnglish
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AmenityCourt", b =>
                {
                    b.Property<Guid>("AmenitiesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AmenitiesId", "CourtsId");

                    b.HasIndex("CourtsId");

                    b.ToTable("AmenityCourt");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("bit");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LockerRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurfaceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LockerRoomId")
                        .IsUnique()
                        .HasFilter("[LockerRoomId] IS NOT NULL");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.LockerRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Showers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LockerRooms");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Administrator", b =>
                {
                    b.HasBaseType("GestionComplejo2C.Domain.Entities.User");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Customer", b =>
                {
                    b.HasBaseType("GestionComplejo2C.Domain.Entities.User");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AmenityCourt", b =>
                {
                    b.HasOne("GestionComplejo2C.Domain.Entities.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionComplejo2C.Domain.Entities.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Booking", b =>
                {
                    b.HasOne("GestionComplejo2C.Domain.Entities.Court", null)
                        .WithMany("Bookings")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionComplejo2C.Domain.Entities.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Court", b =>
                {
                    b.HasOne("GestionComplejo2C.Domain.Entities.LockerRoom", "LockerRoom")
                        .WithOne("Court")
                        .HasForeignKey("GestionComplejo2C.Domain.Entities.Court", "LockerRoomId");

                    b.Navigation("LockerRoom");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Court", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.LockerRoom", b =>
                {
                    b.Navigation("Court");
                });

            modelBuilder.Entity("GestionComplejo2C.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
